language: node_js
node_js:
- '8'
script:
- yarn test
before_deploy: "cd directory && yarn && yarn build && cd .."
deploy:
- provider: npm
  skip_cleanup: true
  email: joel@oblador.se
  api_key:
    secure: "G+1tMhNwfVhVV7Lca6fJ9429Mvg/+XK9inOzT9xB21TI//FL7yMjLUtqcDtH8foYUD1xQt6sCyxbrAyvJVU/LeGH/OfwKYYHlqVJKIuNYuBagGIC1Om2FxNPE0WCiEeVS61ARl1C/A9Jyk0VFQLzm/hkt1WmtJqJt9vScmHRjYIuSZEIiBIxsQ0BcsK1yAbvP4hZbNv2Y9M/X9SrJscvxqiDIxP6HJDIK+Rux8sywVjiBsuZnSqSfNLzfeLdLwODdhAfhwD9+bBE8wMNM0bHkm73KHqtRYU1aE950yPOxxOiQWl6MFrBf/i0lU3RyD7FFftjSNJm0yIycszEuj95OVWk/aTSRF8fAruA71nyGtQIZuJ3lS6e5I2zSIXOD2wruMSRabZLP1wjhpX1j9wZMPAJByDLnvqV53UETVT0IaUwUCYq52t8e8TCfB3OfBGKPM4cfNavxG0YurBJeXZh2QkUzR4CpLpPOR1rObmUHffHN7DEi6EWzVFiLVhFeY1kPdznhZ+T2MUxDpKFrlu5YOkUwHBnZ5Gc4Wi4GTcaqooN25mFqV4S0vL2ZMPfFSQ9fnNXjTO+ufrH7WjvNyDLEQ3Pp79Ziprs2eMkPCktZrChbleBEoyFdNfgLzyRc2FgFZ2nSPSHGCJKE8k+Q3BZ3fqNmUsZMpMaHIqbfA2JSUg="
  on:
    tags: true
    repo: oblador/react-native-vector-icons
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
- provider: pages
  skip_cleanup: true
  local_dir: "directory/build"
  github_token:
    secure: "dErvAbyystT3eO9BZoOqxNaxKgFdMu3RyeogEEBAinu1iSQcylH3+ZSdN5IDvfShRnoeuc61aukMHdgHgSoomherhN2yJc2GnISkhCP1w4qfTlJGc1JqEXoKNBcQ7GGKNxeABxH3LUwooGAPppfPZ2WMe1meg5363t2IcaWbDGXKdHReyBkT9S1ZW1J2bEUXI/UKilukNQgDdwbhzyalEgGMl2BtaOo9CCyBmBp77KgRjO2175b5bHoYXTLPcjCR697lJq7K6GhFoPolexofv1zM/5IPSPGVoHnG9sqiMCWME+fvysFbgcUQQbfhX8jEZtbXuyM4Q/KCXRtOkxtJBa/ZNKDM7RIA+odMed7Usxz53O13/PUCFozURWoDG83paWLuBKl5TFMWxUuGFVaDGv/GugSLrjp9Hz6bGNBXxlRrwhrByqSsP5vLyDvCbxFdnUp5u+DfSKolW1D0chkJ1L0RX4tXuq+oR0gwVMY336angh4JCE989bU04HGxxuo11KL95yndzRdxfXEpWE+RRP1HkUIp/jsAVErhfmpZrpb+O1AceEgT3H8yb3F1uwdNI5YsV7Wc2Kmf2LxP7QBzkPMRY2locCPyks3e9vnjx/D9CQzFMjroh+zhC5eUcmO5IjpYWzxz6L6vdw+n9xwOj2rlmH1/z18RI5RMf2/idRs="
  on:
    tags: true
    repo: oblador/react-native-vector-icons
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
